FROM node:20 AS build
WORKDIR /app
#Тепер .env отримується з кореня проєкту, а не з папки frontend, як було у попередній версії
COPY frontend/package*.json ./ 
RUN npm ci

COPY frontend/ ./

ARG VITE_API_URL
ENV VITE_API_URL=$VITE_API_URL

RUN echo "Building with API URL: $VITE_API_URL"

RUN npm run build

FROM nginx:alpine
COPY --from=build /app/dist /usr/share/nginx/html

EXPOSE 80

CMD ["nginx", "-g", "daemon off;"]