// <auto-generated />
using BankMap.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BankMap.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.3")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BankMap.Domain.Entities.Branch", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("IsRegular")
                        .HasColumnType("bit");

                    b.Property<bool>("IsTemporaryClosed")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("BankBranches", (string)null);
                });

            modelBuilder.Entity("BankMap.Domain.Entities.Branch", b =>
                {
                    b.OwnsOne("BankMap.Domain.Entities.Branch+AddressInfo", "Address", b1 =>
                        {
                            b1.Property<int>("BranchId")
                                .HasColumnType("int");

                            b1.Property<string>("City")
                                .IsRequired()
                                .HasMaxLength(100)
                                .HasColumnType("nvarchar(100)");

                            b1.Property<string>("FullAddress")
                                .IsRequired()
                                .HasMaxLength(300)
                                .HasColumnType("nvarchar(300)");

                            b1.Property<double>("Latitude")
                                .HasColumnType("float");

                            b1.Property<double>("Longitude")
                                .HasColumnType("float");

                            b1.HasKey("BranchId");

                            b1.ToTable("BranchAddresses", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.OwnsMany("BankMap.Domain.Entities.Branch+CashDesk", "CashDesks", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("BranchId")
                                .HasColumnType("int");

                            b1.Property<string>("Description")
                                .IsRequired()
                                .HasMaxLength(200)
                                .HasColumnType("nvarchar(200)");

                            b1.Property<int>("ExternalId")
                                .HasColumnType("int");

                            b1.HasKey("Id");

                            b1.HasIndex("BranchId");

                            b1.ToTable("BranchCashDesks", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BranchId");

                            b1.OwnsMany("BankMap.Domain.Entities.Branch+CashDesk+CashWorkDay", "WorkDays", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("CashDeskId")
                                        .HasColumnType("int");

                                    b2.Property<int>("Day")
                                        .HasColumnType("int");

                                    b2.Property<string>("From")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<string>("To")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("CashDeskId");

                                    b2.ToTable("CashDeskWorkingDays", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("CashDeskId");
                                });

                            b1.Navigation("WorkDays");
                        });

                    b.OwnsMany("BankMap.Domain.Entities.Branch+ContactPhone", "Phones", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("BranchId")
                                .HasColumnType("int");

                            b1.Property<string>("Number")
                                .IsRequired()
                                .HasMaxLength(20)
                                .HasColumnType("nvarchar(20)");

                            b1.Property<string>("OperatorCode")
                                .IsRequired()
                                .HasMaxLength(10)
                                .HasColumnType("nvarchar(10)");

                            b1.HasKey("Id");

                            b1.HasIndex("BranchId");

                            b1.ToTable("BranchPhones", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BranchId");
                        });

                    b.OwnsMany("BankMap.Domain.Entities.Branch+WorkSchedule", "Schedules", b1 =>
                        {
                            b1.Property<int>("Id")
                                .ValueGeneratedOnAdd()
                                .HasColumnType("int");

                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b1.Property<int>("Id"));

                            b1.Property<int>("BranchId")
                                .HasColumnType("int");

                            b1.Property<string>("WorkStation")
                                .IsRequired()
                                .HasMaxLength(50)
                                .HasColumnType("nvarchar(50)");

                            b1.HasKey("Id");

                            b1.HasIndex("BranchId");

                            b1.ToTable("BranchSchedules", (string)null);

                            b1.WithOwner()
                                .HasForeignKey("BranchId");

                            b1.OwnsMany("BankMap.Domain.Entities.Branch+WorkSchedule+WorkingDay", "Days", b2 =>
                                {
                                    b2.Property<int>("Id")
                                        .ValueGeneratedOnAdd()
                                        .HasColumnType("int");

                                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b2.Property<int>("Id"));

                                    b2.Property<int>("Day")
                                        .HasColumnType("int");

                                    b2.Property<string>("From")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.Property<int>("ScheduleId")
                                        .HasColumnType("int");

                                    b2.Property<string>("To")
                                        .IsRequired()
                                        .HasColumnType("nvarchar(max)");

                                    b2.HasKey("Id");

                                    b2.HasIndex("ScheduleId");

                                    b2.ToTable("BranchWorkingDays", (string)null);

                                    b2.WithOwner()
                                        .HasForeignKey("ScheduleId");

                                    b2.OwnsMany("BankMap.Domain.Entities.Branch+WorkSchedule+BreakInterval", "Breaks", b3 =>
                                        {
                                            b3.Property<int>("Id")
                                                .ValueGeneratedOnAdd()
                                                .HasColumnType("int");

                                            SqlServerPropertyBuilderExtensions.UseIdentityColumn(b3.Property<int>("Id"));

                                            b3.Property<string>("From")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<string>("To")
                                                .IsRequired()
                                                .HasColumnType("nvarchar(max)");

                                            b3.Property<int>("WorkingDayId")
                                                .HasColumnType("int");

                                            b3.HasKey("Id");

                                            b3.HasIndex("WorkingDayId");

                                            b3.ToTable("BranchBreaks", (string)null);

                                            b3.WithOwner()
                                                .HasForeignKey("WorkingDayId");
                                        });

                                    b2.Navigation("Breaks");
                                });

                            b1.Navigation("Days");
                        });

                    b.Navigation("Address")
                        .IsRequired();

                    b.Navigation("CashDesks");

                    b.Navigation("Phones");

                    b.Navigation("Schedules");
                });
#pragma warning restore 612, 618
        }
    }
}
